name: Tests

on:
  push:
    branches:
      - main
  create:
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    # Run every day at 7:42am UTC.
    - cron:  '42 7 * * *'
  workflow_dispatch:

jobs:
  benchopt_dev:
    uses: YanisLalou/skada-bench/.github/workflows/test_benchmarks.yml@main
    with:
      benchopt_branch: benchopt@main
  benchopt_release:
    uses: YanisLalou/skada-bench/.github/workflows/test_benchmarks.yml@main
    with:
      benchopt_version: latest
  lint:
    uses: benchopt/template_benchmark/.github/workflows/lint_benchmarks.yml@main
